source "https://rubygems.org"

# parser emits warnings upon load which is not appropriate for this
# project. unparser, which depends on parser, thusly causes the same
# problem. $stderr needs to be temporarily suppressed while loading
# either of these gems which requires custom handling. Therefore we
# cannot rely on Bundler to require these gems for us.
#
# See lib/burdock/parser.rb and lib/burdock/unparser.rb
gem "parser", "2.5.0.3", require: false
gem "unparser", "0.2.7 ", require: false
gem "yajl-ruby"
gem "yard"

group :development do
  gem "pry"
  gem "pry-doc"
end

gemspec
